# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 189b667b9e479cab3530499c930e5ce668691b2613713b2422ecdc29895ab593ee89b621246b91acefc44656d784c9c185fe40a597ca92fd5152525586beeb44

test:
  secret_key_base: 2c4fa49764167f2f713e9ad32951c6c6576d9810d727f0520845e44f8704f2c64204dfc2e4126900218f45516d2d4e3f969ef2e5f7dadfd8e15ccae94584b789

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
